[package]
name = "the_jouch"
version = "0.1.0"
authors = ["David <gw.chip.gw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
tokio = "1.9"
mini-redis = "*"
chrono = "0.4"
serde = "1.0"
rustbreak = { version = "2", features = ["ron_enc"] }
ron = "*"
merge = "0.1"
